version: '3.1'

services:

  db:
    image: postgres
    restart: always
    expose:
      - 5400
    ports:
      - 5400:5432
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - back-tier

volumes:
  postgres: {}

networks:
  back-tier:
    driver: bridge